let WRITE = true;
let offset=0;
let cnt=0;
let filename = "montmini.fnt";
let filesize = 4257;
let offstr = "";
let lenstr = "";
let 
digit = atob("GSHE/wAAec6mMU1r171ZzkUpQQiSlOMYUYyCEK5zaUoIQjjGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACdyIo9cAAAAAAAAAahERERHzsAAAAAAA0RERERERFGAAAAAAMRERERERER8gAAAA0RER+D3IUREfkAAAvxERiwAAAvERGgAAChERhwAAAAZBER4AB1ERRwAAAAACERGAANEREwAAAAAABBEVcAoRFbAAAAAAANERHQDxEaAAAAAAAAdREaBxERwAAAAAAAAEERgJERHQAAAAAAAAgRFAIREeAAAAAAAAChEUDhERIAAAAAAAAMERUCEREgAAAAAAAAwRHwYREdAAAAAAAACBEUCxERMAAAAAAAAIERgAERHAAAAAAAAAQRGgBBEUAAAAAAAAkRETADEREgAAAAAADBERYAYREYAAAAAAC/ERQAAEEREgAAAAAMERHAAA4REV4AAAAMERH7AAAIERETYAcoEREdAAAAlBEREfRREREYAAAAAJQREREREREacAAAAAC4ERERERFcAAAAAAAABq8RERQ7AAAAAAAAAAALImcAAAAAAAAAAAAAAAAAAAAAAAA=");
if(WRITE)_S.write(filename, digit, offset, filesize);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
digit = atob("ECHE/wAAec7PewxjaUpVrde9SUoUpetaWc7znMtaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQzMzMzNAAABhEREREVAAAGERERERUAAAYRERERFQAACTMzOBEVAAAAAAACERUAAAAAAAIRFQAAAAAAAhEVAAAAAAACERUAAAAAAAIRFQAAAAAAAhEVAAAAAAACERUAAAAAAAIRFQAAAAAAAhEVAAAAAAACERUAAAAAAAIRFQAAAAAAAhEVAAAAAAACERUAAAAAAAIRFQAAAAAAAhEVAAAAAAACERUAAAAAAAIRFQAAAAAAAhEVAAAAAAACERUAAAAAAAIRFQAAAAAAAhEVAAAAAAACERUAAAAAAAIRFQAAAAAAAhEYAAAAAAAAAAAAAAAAAAAAAAAA");
if(WRITE)_S.write(filename, digit, offset);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
digit = atob("FyHE/wAAec6iENe9TWuylOtabWsYxopSEIRZznGM4xhlKQhCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADkrFWm8gAAAAAAKjERERERhCAAAABoERERERERE+AAAKEREREREREREyAAcRERs6b5QxERFQANMRFdAAAABhERHQACUXAAAAAABxER8AAA4AAAAAAAIREXAAAAAAAAAAAAgRGgAAAAAAAAAAAhERQAAAAAAAAAAA8REZAAAAAAAAAAAMERHQAAAAAAAAAA8REVAAAAAAAAAADoERvgAAAAAAAAANMREUAAAAAAAAAA0xERwAAAAAAAAADjERFQAAAAAAAAAOgREVAAAAAAAAAA6BERUAAAAAAAAADoERFQAAAAAAAAAPsREcAAAAAAAAAA+xERoAAAAAAAAAD7ERGgAAAAAAAAAJsREXAAAAAAAAAAkRERcAAAAAAAAACREREYiIiIiIiIUAURERERERERERETAFEREREREREREREwBRERERERERERERUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");
if(WRITE)_S.write(filename, digit, offset);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
digit = atob("FyHE/wAAec7rWgxj05xhCKYxGMZpSlnOJCGOc01rNKXnObKUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIMzMzMzMzMzMzUABBEREREREREREaAAQRERERERERERGgAEERERERERERERoACDMzMzMzMxERGwAAAAAAAAAAMREUAAAAAAAAAADhERdQAAAAAAAAAKcRF6AAAAAAAAAAXRERgAAAAAAAAAAEERHAAAAAAAAAAAsREfAAAAAAAAAACBER1QAAAAAAAAAKkREfhQAAAAAAAADhERERHWAAAAAAAA4REREREbUAAAAAAKd5EREREbAAAAAAAAAFo3EREeAAAAAAAAAAALERHQAAAAAAAAAABdERkAAAAAAAAAAAAhERoAAAAAAAAAAA4REeAAAAAAAAAAAIERFgDsAAAAAAAADxERUFcdYAAAAAAMERHQAxERSKAAAGQRERgAcREREX1NkRERFAAOcREREREREREdUAAFtxERERERERtQAAAAUvcREREdygAAAAAAAAqu5qUAAAAAAAAAAAAAAAAAAAAAA=");
if(WRITE)_S.write(filename, digit, offset);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
digit = atob("GiHE/wAAec7DGBSlTWtZzutaYQjXvSQhIACKUpa1rnPPe/OcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlmZiAAAAAAAAAAAACVERggAAAAAAAAAAAHwRFZAAAAAAAAAAAADxERYAAAAAAAAAAAAEERHwAAAAAAAAAAAAsREccAAAAAAAAAAAAoERWQAAAAAAAAAAAHMREbAAAAAAAAAAAADhER4AAAAAAAAAAAALERE6AAAAAAAAAAAAlREYIAAAAAAAAAAAB4ERGQAAAAAAAAAAAA8REWAAB8zMkAAAAABBER8AAAcREZAAAAALERHHAAAHERGQAAAAlREVkAAABxERkAAAB8ERGwAAAAcREZAAAA4REeAAAAAHERGQAABhEREzMzMzMxERwzM78RERERERERERERERFPERERERERERERERERTxEREREREREREREREUIiIiIiIiIikREbIiKgAAAAAAAAAJERGQAAAAAAAAAAAACRERkAAAAAAAAAAAAAkREZAAAAAAAAAAAAAJERGQAAAAAAAAAAAACRERkAAAAAAAAAAAAAkREZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
if(WRITE)_S.write(filename, digit, offset);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
digit = atob("GCHE/wAAec7rWmUpDGOmMRjG85xZzra1ilIoQs97EIRta3WtAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABERERERERERAAAAAMREREREREREVAAAAUREREREREREVAAAAsREREREREREVAAAAIRGURERERERAAAAA4RHQAAAAAAAAAAAA0RHAAAAAAAAAAAAAcRHgAAAAAAAAAAAA8RGgAAAAAAAAAAAAYRGwAAAAAAAAAAAAEREwAAAAAAAAAAADERGrVVMAAAAAAAAFEREREREZ2wAAAAALEREREREREfsAAAACERERERERERGgAAAD3d3dd5YRERGDAAAAAAAAAABcYREZAAAAAAAAAAAANhERUAAAAAAAAAAABRERQAAAAAAAAAAAAGER0AAAAAAAAAAAAHERcAAAAAAAAAAAAGER0AANUAAAAAAABRERwAChHTAAAAAANhERUABhEW5QAAAOYREfAAQREREW9/YREREbAADRERERERERERGgAAALcREREREREZUAAAAAA+eBEREY2gAAAAAAAAADU1MwAAAAAAAAAAAAAAAAAAAAAA");
if(WRITE)_S.write(filename, digit, offset);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
digit = atob("GCHE/wAAec7znIYxspQwhFnOxzkYxiAAKELrWte94xhpSnWtAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3rUiVbMAAAAAAAB0YRERERHL0JAAAJQRERERERERMJAADfERERERERESAJAA3BERHFtzflYXAJAAQRERWQAAAA3gAJAOERHDAAAAAAAAAJAPEREwAAAAAAAAAJAxERQAAAAAAAAAAJCxEW0AAAAAAAAAAJDxEUAAAAAAAAAAAABhEVAAk+u6OQAAAA0REbA0gRERGFMAAA0REaURERERERFZAAcREfEREREREREUAAcRERERxLq1gRERsA0REREVAAAA1RERiQkRERGwAAAAAFERGwDBERUAAAAAAJgRFQAhERcAAAAAAAIREgBRERMAAAAAAAURHwCxERsAAAAAAAIRFACcERIAAAAAANYRFQAOERFQAAAAACERFwAJ8REU0AAA1BER8AAAoRERH1tUEREWMAAADhEREREREREeAAAAAH8RERERER8wAAAAAAm0YRERFOkAAAAAAAAAnTN9kAAAAAAAAAAAAAAAAAAAAA");
if(WRITE)_S.write(filename, digit, offset);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
digit = atob("GSHE/wAAec7rWgxj172Oc6YxpzHDGOMYaUphCKpSTWtZzsc5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMzMzMzMzMzMzYAsRERERERERERERFQCxEREREREREREREVALERERERERERERERUAsREVMzMzMzM0ERFgCxER8AAAAAAI4RFAALERHwAAAAAA0REfAAsREfAAAAAAtBEUAACxER8AAAAAAhERwAAAMzOAAAAAAEERSwAAAAAAAAAAAKERHQAAAAAAAAAAAAQRHoAAAAAAAAAAAAYREVAAAAAAAAAAAABRERkAAAAAAAAAAACRERQAAAAAAAAAAAAFERHwAAAAAAAAAAAL4RFAAAAAAAAAAAAAMREcAAAAAAAAAAAAtBEUsAAAAAAAAAAADBERMAAAAAAAAAAAAEER6wAAAAAAAAAAAPERFQAAAAAAAAAAAAQREZAAAAAAAAAAAAYREVAAAAAAAAAAAABRERYAAAAAAAAAAACOERQAAAAAAAAAAAAFERGgAAAAAAAAAAAL4RFAAAAAAAAAAAAAoRETAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");
if(WRITE)_S.write(filename, digit, offset);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
digit = atob("GSHE/wAAec7HOfOcbWthCNe9Wc6iEBjGkpQsY+taz3tFKeMYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA69ozrc8AAAAAAAAMYRERERETIAAAAACDEREREREREaAAAACGERERERERERGgAAANEREaLwX8YRERIAAIcRESAAAAAEEREwAAIREbAAAAAAChERUADBER8AAAAAAMERHgAMERGAAAAAAAIREeAAIRESAAAAAABBERgAD3ERaAAAAADpERYAAA0RETIAAAXGERHAAACGEREWrdORERHQAAAA+hERERERERFAAAAABUEREREREREbUAAAAmERERERERERFoAADnERGdL1XioRERZQAKERGlAAAAAOYREbAPERE1AAAAAAD5ERYAIRESAAAAAAAA0REYDBER8AAAAAAADBER4MERHgAAAAAAALERHgIREbAAAAAAAAMREVCHERcgAAAAAAQREWAA0REZtQAAAP0RERwAD2EREZrUvTERERMAAA5hEREREREREROAAAAP0REREREREXRQAAAAAOQxERERc8gAAAAAAAAAX+4u9QAAAAAAAAAAAAAAAAAAAAAAA=");
if(WRITE)_S.write(filename, digit, offset);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
digit = atob("GSHE/wAAec7nOde9ohBZzkEIkpQIQk1rNKXDGGUpEISGMTjGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAidd32EAAAAAAAABp8RERERF8AAAAAADKERERERERGQAAAACzERERERERERkAAAAKERFZxm6XERESAAAIERGrAAAACRERoAAAcRFcAAAAAAgREYAAAxEdAAAAAAADERoABhERgAAAAAAA0REeAEERGAAAAAAACRERgABREZAAAAAAAHERGQADERNAAAAAAMEREdAAkREXAAAAAI8RERoACxERE4AAbJEREREwAAkRERFTpREREREVAAAJERERERERE9ERMAAACDERERERWWcRGgAAAAYtox83mwChEXAAAAAAAAAAAAAFER0AAAAAAAAAAAAMERGAAAAAAAAAAAAAcREUAAAAAAAAAAAA4REXAAAAAAAAAAAAahERgAAAAAAAAAAAwxERcAAAAIqGAAALkRER+wAAAAoR+n2lERERWAAAAAgRERERERERPAAAAACREREREREVdAAAAAAAuTERERE5sAAAAAAAAAAL6OsAAAAAAAAAAAAAAAAAAAAAAAAAA=");
if(WRITE)_S.write(filename, digit, offset);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
print(`Filesize: ${offset}`);
print(`Offsets: [${offstr}]`);
print(`Lengths: [${lenstr}]`);
/*
function getDigit(d) {
return _S.read("montmini.fnt",
[0, 449, 749, 1165, 1581, 2046, 2478, 2910, 3359, 3808 ][d],
[449, 300, 416, 416, 465, 432, 432, 449, 449, 449][d]
);
}
digitStart = ['1', '25', '41', '64', '88', '114', '138', '161', '186', '211'];
digitEnd = ['26', '41', '64', '87', '114', '138', '162', '186', '211', '236'];
*/
