let imgD0 = {
  width : 26, height : 40, bpp : 2,
  transparent : -1,
  palette : new Uint16Array([0,65535,50712,23275]),
  buffer : E.toArrayBuffer(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAD7wAAAAADWpcAAAAAnADrAAAAGAAAnAAACgAAAoAAAoAAAAoAANwAAAAcAAoAAAADgANAAAAABwA4AAAAAKABwAAAAA0AEAAAAAAcDQAAAAACwKAAAAAAOAsAAAAAA4CwAAAAADQLAAAAAANAsAAAAAA0CwAAAAADQLAAAAAAOAoAAAAAA4DgAAAAACwNAAAAAALAHAAAAAAQAoAAAAAOADQAAAAAsABwAAAANAANAAAAAoAAKAAAANAAA3AAADcAAA3AAA3AAAA2AANwAAAA5/9cAAAAAOmsAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="))
};
let imgD1 = {
    width : 19, height : 40, bpp : 2,
  transparent : -1,
  palette : new Uint16Array([0,65535,59164,19017]),
  buffer : E.toArrayBuffer(atob("AAAAAAAAAAAAAAAAAAAAAAMAAAAA5wAAADncAAADYHAAAOsBwAADwAcAAAAAHAAAAABwAAAAAcAAAAAHAAAAABwAAAAAcAAAAAHAAAAABwAAAAAcAAAAAHAAAAABwAAAAAcAAAAAHAAAAABwAAAAAcAAAAAHAAAAABwAAAAAcAAAAAHAAAAABwAAAAAcAAAAAHAAAAABwAAAAAcAAAAAHAAAAABwAAAAAcAAAAALAAAAAAAAAAAAAAAAAAAAAA=="))

};
let imgD2 = {
    width : 25, height : 40, bpp : 2,
  transparent : -1,
  palette : new Uint16Array([0,65535,12678,33840]),
  buffer : E.toArrayBuffer(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAv+AAAAALV9XgAAANcAC3AAANwAADcAANgAAAJwABgAAAAmAAAAAAADQAAAAAAAmAAAAAAABwAAAAAAA8AAAAAAANAAAAAAADQAAAAAAA8AAAAAAAPAAAAAAABgAAAAAADQAAAAAACcAAAAAAAcAAAAAAA8AAAAAAAcAAAAAACcAAAAAACcAAAAAACcAAAAAADcAAAAAADcAAAAAADcAAAAAADcAAAAAADYAAAAAABYAAAAAAJQAAAAAAJQAAAAAAJQAAAAAANaqqqqqgBVVVVVVUAAAAAAAAAAAAAAAAAAAAAAAAAA=="))

};
let imgD3 = {
  width : 25, height : 40, bpp : 2,
  transparent : -1,
  palette : new Uint16Array([0,65535,42292,12710]),
  buffer : E.toArrayBuffer(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAOqqqqqgADqqqqVYAAAAAADYAAAAAADYAAAAAAAUAAAAAAAUAAAAAAAUAAAAAAAXAAAAAAAnAAAAAAAnAAAAAAAnAAAAAAAmwAAAAAAJWgAAAAAADlwAAAAAAAnAAAAAAACcAAAAAAAJwAAAAAAAoAAAAAAANwAAAAAAAYAAAAAAAKAAAAAAADQAAAAAAA0AAAAAAANAAAAAAACQAAAAAAAoAAAAAAAHAAAAAAAJAAAAAAANwADAAAANgADYAAANgAANsAAJgAAAJa+lwAAAA6VrAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="))
 };
let imgD4 = {
    width : 30, height : 40, bpp : 2,
  transparent : -1,
  palette : new Uint16Array([0,65535,23243,27469]),
  buffer : E.toArrayBuffer(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAANgAAAAAAAAlgAAAAAAAAVgAAAAAAABRgAAAAAAANhgAAAAAAA3BgAAAAAACcBgAAAAAABQBgAAAAAAFABgAAAAAA0ABgAAAAADYABgAAAAAJwABgAAAAAFAABgAAAAAUAABgAAAADQAABgAAAANgAABgAAAAnAAABgAAACcAAABgAAABQAAABgAAANAAAABgAAA2AAAABgAACcAAAABgAAJwAAAABgAAFAAAAABgAAX/////96gAVVVVVVVVQAAAAAAABgAAAAAAAABgAAAAAAAABgAAAAAAAABgAAAAAAAABgAAAAAAAABgAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"))
};
let imgD5 = {
    width : 25, height : 40, bpp : 2,
  transparent : -1,
  palette : new Uint16Array([0,65535,50712,50744]),
  buffer : E.toArrayBuffer(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAKqqqqqAAB/+qqqoAAQAAAAAAAEAAAAAAAJAAAAAAACQAAAAAAAsAAAAAAAKAAAAAAADgAAAAAAAYAAAAAAAEAAAAAAABAAgAAAAAQlVWAAAAmYACmAAAJwAAAcAACgAAACwAAAAAAAOAAAAAAAAQAAAAAAALAAAAAAAAQAAAAAAAEAAAAAAACgAAAAAAAoAAAAAAAKAAAAAAADgAAAAAAAQAAAAAAAkAAAAAAAOAAAAAAAJAAAAAAABAACQAAAJgAAJgAAJgAAANoC2AAAAALVoAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="))
};
let imgD6 = {
    width : 26, height : 40, bpp : 2,
  transparent : -1,
  palette : new Uint16Array([0,65535,23275,44405]),
  buffer : E.toArrayBuffer(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArAAAAAACV8AAAAACWAAAAAAA2AAAAAAANgAAAAAADwAAAAAAAmAAAAAAABgAAAAAAA8AAAAAAABgAAAAAAA8AAAAAAABgAAAAAAAkAK/4AAACwJXtWAAAOJYAAlgAAacAAANgABmAAAAJAAlwAAAAPACUAAAAAGAJwAAAAA8AmAAAAACQCQAAAAABgJAAAAAAGAkAAAAAAYCQAAAAABgBgAAAAAEAGAAAAACwAkAAAAAGAAcAAAADQACYAAAAmAACYAAAJgAACcAADYAAAC3qreAAAAAtV6AAAAAAAAAAAAAAAAAAAAAAAAAAAAA="))
};
let imgD7 = {
    width : 25, height : 40, bpp : 2,
  transparent : -1,
  palette : new Uint16Array([0,65535,35953,50712]),
  buffer : E.toArrayBuffer(atob("AAAAAAAAAAAAAAAAAAAAAAAAACqqqqqqgAv///9VcAAAAAAAGAAAAAAAJAAAAAAABgAAAAAAAQAAAAAAA8AAAAAAAGAAAAAAAJAAAAAAABgAAAAAACQAAAAAAA8AAAAAAAGAAAAAAALAAAAAAABgAAAAAACQAAAAAAA4AAAAAAAEAAAAAAAPAAAAAAABgAAAAAACwAAAAAAAYAAAAAAAkAAAAAAAOAAAAAAABAAAAAAACwAAAAAAAYAAAAAAAkAAAAAAAOAAAAAAAJAAAAAAADwAAAAAAAYAAAAAAAsAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="))
};
let imgD8 = {
    width : 26, height : 40, bpp : 2,
  transparent : -1,
  palette : new Uint16Array([0,65535,4258,4226]),
  buffer : E.toArrayBuffer(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAKWgAAAAACVVgAAAAAWAJQAAAAJgABQAAACYAAJgAAAJAAAGAAAAUAAAUAAABQAABQAAAJAAAGAAAAmAACYAAAAXAAFAAAAAWAJcAAAADVVWAAAAAJVVYAAAAJWAKWAAACWAAAWAAAlAAAAmAABQAAAAnAAkAAAAAUABgAAAACYAnAAAAABgCQAAAAAFAFAAAAAAkAUAAAAACQCQAAAAAJAJAAAAAAUAmAAAAABgAUAAAAAkACYAAAAJgABYAAAAUAABYAAA1gAABYAAJYAAACVqpYAAAAAlVaAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="))
};
let imgD9 = {
  width : 26, height : 40, bpp : 2,
  transparent : -1,
  palette : new Uint16Array([0,65535,61277,21130]),
  buffer : E.toArrayBuffer(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/8AAAAAOapbAAAADbAA6wAAArAAANwAAOAAAANwADcAAAAOAALAAAAALADgAAAAA4ALAAAAAAsAsAAAAACwBwAAAAAOAEAAAAAA4AcAAAAACgCwAAAAAKAOAAAAAAYA3AAAAANgAoAAAAAaAAsAAAAKsADcAAACiwADbAADoHAADm8PnDQAAA+VrAOAAAAAAAAsAAAAAAANAAAAAAAAoAAAAAAANwAAAAAAAoAAAAAAAOAAAAAAADcAAAAAAA3AAAAAAANwAAAAAAOsAAAAAD6sAAAAAAqsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="))
};

