let imgD0 = {
  width : 26, height : 40, bpp : 2,
  transparent : -1,
  palette : new Uint16Array([0,65535,50712,23275]),
  buffer : E.toArrayBuffer(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAD7wAAAAADWpcAAAAAnADrAAAAGAAAnAAACgAAAoAAAoAAAAoAANwAAAAcAAoAAAADgANAAAAABwA4AAAAAKABwAAAAA0AEAAAAAAcDQAAAAACwKAAAAAAOAsAAAAAA4CwAAAAADQLAAAAAANAsAAAAAA0CwAAAAADQLAAAAAAOAoAAAAAA4DgAAAAACwNAAAAAALAHAAAAAAQAoAAAAAOADQAAAAAsABwAAAANAANAAAAAoAAKAAAANAAA3AAADcAAA3AAA3AAAA2AANwAAAA5/9cAAAAAOmsAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="))
};
let imgD1 = {
    width : 19, height : 40, bpp : 2,
  transparent : -1,
  palette : new Uint16Array([0,65535,59164,19017]),
  buffer : E.toArrayBuffer(atob("AAAAAAAAAAAAAAAAAAAAAAMAAAAA5wAAADncAAADYHAAAOsBwAADwAcAAAAAHAAAAABwAAAAAcAAAAAHAAAAABwAAAAAcAAAAAHAAAAABwAAAAAcAAAAAHAAAAABwAAAAAcAAAAAHAAAAABwAAAAAcAAAAAHAAAAABwAAAAAcAAAAAHAAAAABwAAAAAcAAAAAHAAAAABwAAAAAcAAAAAHAAAAABwAAAAAcAAAAALAAAAAAAAAAAAAAAAAAAAAA=="))

};
let imgD2 = {
    width : 25, height : 40, bpp : 2,
  transparent : -1,
  palette : new Uint16Array([0,65535,12678,33840]),
  buffer : E.toArrayBuffer(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAv+AAAAALV9XgAAANcAC3AAANwAADcAANgAAAJwABgAAAAmAAAAAAADQAAAAAAAmAAAAAAABwAAAAAAA8AAAAAAANAAAAAAADQAAAAAAA8AAAAAAAPAAAAAAABgAAAAAADQAAAAAACcAAAAAAAcAAAAAAA8AAAAAAAcAAAAAACcAAAAAACcAAAAAACcAAAAAADcAAAAAADcAAAAAADcAAAAAADcAAAAAADYAAAAAABYAAAAAAJQAAAAAAJQAAAAAAJQAAAAAANaqqqqqgBVVVVVVUAAAAAAAAAAAAAAAAAAAAAAAAAA=="))

};
let imgD3 = {
  width : 25, height : 40, bpp : 2,
  transparent : -1,
  palette : new Uint16Array([0,65535,42292,12710]),
  buffer : E.toArrayBuffer(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAOqqqqqgADqqqqVYAAAAAADYAAAAAADYAAAAAAAUAAAAAAAUAAAAAAAUAAAAAAAXAAAAAAAnAAAAAAAnAAAAAAAnAAAAAAAmwAAAAAAJWgAAAAAADlwAAAAAAAnAAAAAAACcAAAAAAAJwAAAAAAAoAAAAAAANwAAAAAAAYAAAAAAAKAAAAAAADQAAAAAAA0AAAAAAANAAAAAAACQAAAAAAAoAAAAAAAHAAAAAAAJAAAAAAANwADAAAANgADYAAANgAANsAAJgAAAJa+lwAAAA6VrAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="))
 };
let imgD4 = {
  
};
let imgD5 = {
  
};
let imgD6 = {
  
};
let imgD7 = {
  
};
let imgD8 = {
  
};
let imgD9 = {
  
};

