// Agency font (slim, squared)
let myPal = new Uint16Array([0,0xfff,0xccc,0x888]); //[0,65535,65535,65535]);
const startX=[0,20,40,60],startY=[16,16,16,16],nmX=[16,42,88,126],nmY=[12,12,12,12];let rotate=!1;
let d0 = {
  width : 18, height : 42, bpp : 2,
  transparent : -1,
  palette : myPal, //new Uint16Array([0,65535,59196,6339]),
  buffer : E.toArrayBuffer(atob("AAAAAADqqqqwNVVVVcJVVVVYJb//5YJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJYAAJYJb//5YJVVVVYJVVVVYClVVWgAAAAAAAAAAAA"))
},d1 = {
  width : 18, height : 42, bpp : 2,
  transparent : -1,
  palette : myPal, //new Uint16Array([0,65535,38066,25388]),
  buffer : E.toArrayBuffer(atob("AAAAAAAAAAAAAANUAAAAJUAAAAJUAAAAFUAAAAFUAAAA1UAAAA1UAAAAlUAAAAlUAAAAVUAAAA5UAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAJUAAAAAAAAAAAAAA"))
},d2 = {
  width : 18, height : 42, bpp : 2,
  transparent : -1,
  palette :  myPal, //new Uint16Array([0,65535,6339,59196]),
  buffer : E.toArrayBuffer(atob("AAAAAAC////gDVVVV4JVVVVYJWqqlYJWAAFYJWAAFYJWAAFYJWAAFYJWAAFYJWAAFYJWAAFYJWAAFYAAAAlYAAAA1QAAAAVwAAACVgAAADXAAAAJWAAAANcAAAAlYAAAA1wAAACVgAAADXAAAAJWAAAANcAAAAlYAAAA1wAAACVgAAADVAAAAJXAAAANUAAAAlcAAAA1QAAACVwAAADVAAAAJXqqqoNVVVVcNVVVVcFVVVVcAAAAAAAAAAAA"))
},d3=  {
  width : 18, height : 42, bpp : 2,
  transparent : -1,
  palette : myPal, //new Uint16Array([0,65535,42292,6339]),
  buffer : E.toArrayBuffer(atob("AAAAAACqqqqwJVVVVcJVVVVYFaqqlYFYAAFYFYAAFYFYAAFYFYAAFYFYAAFYFYAAFYFYAAFYFYAAFYAAAAFYAAAAlcAAACVgAAA1WAAACVYAAA5VwAAAlYAAAA1WAAAACVcAAAAlWAAAANVgAAAAlcAAAAFYAAAAFYKoAAFYFYAAFYFYAAFYFYAAFYFYAAFYFYAAFYFYAAFYFYAAFYFYAAFYFb//1YFVVVVYJVVVVcCVVVVgAAAAAAAAAAAA"))
},d4={
  width : 18, height : 42, bpp : 2,
  transparent : -1,
  palette :  myPal, //new Uint16Array([0,65535,61277,19017]),
  buffer : E.toArrayBuffer(atob("AAAAAAAAAKoAAAAFcAAAA1gAAAAlwAAAAVwAAADWAAAACXAAAABXAAAANYAAAAJcAAAA1cAAAA1gAAAAlwVwADVwVwADWAVwACXAVwANUAVwANYAVwAJcAVwA1QAVwAlgAVwAVwAVwDVAAVwCWAAVwBXAAVwNUAAVwJVVVVVFVVVVVFVVVVVAAAAVwAAAAVwAAAAVwAAAAVwAAAAVwAAAAVwAAAAVwAAAAVwAAAAVwAAAAVwAAAAAAAAAAAA"))
},d5={
    width : 18, height : 42, bpp : 2,
  transparent : -1,
  palette :  myPal, //new Uint16Array([0,65535,6339,33840]),
  buffer : E.toArrayBuffer(atob("AAAAAANVVVVwNVVVVQNVVVVQNX///wNUAAAANUAAAAFUAAAAFUAAAAFUAAAAFUAAAAFcAAAAFcAAAAFcAAAAFcAAAAFeqqqAFVVVVgFVVVVQFVVVVQAAAA1QAAAA1QAAAA1QAAAA1QAAAA1QAAAA1QAAAA1QAAAA1QP8AA1QFcAA1QFcAA1QFcAA1QFcAA1QFcAA1QFcAA1QFcAA1QFcAA1QFeqq1QFVVVVQNVVVVwLVVVXgAAAAAAAAAAAA"))
},d6={
  width : 18, height : 42, bpp : 2,
  transparent : -1,
  palette :  myPal, //new Uint16Array([0,65535,61277,21162]),
  buffer : E.toArrayBuffer(atob("AAAAAADqqqrANVVVVgJVVVVcJb//1cJYAAFcJYAAFcJYAAFcJYAAFcJYAAFcJYAAFcJYAAFcJYAAKsJYAAAAJYAAAAJYAAAAJYAAAAJYAAAAJb///AJVVVVgJVVVVcJaqqlcJYAAFcJYAAFcJYAAFcJYAAFcJYAAFcJYAAFcJYAAFcJYAAFcJYAAFcJYAAFcJYAAFcJYAAFcJYAAFcJYAAFcJYAAFcJVVVVcNVVVVcClVVWwAAAAAAAAAAAA"))
},d7 ={
  width : 18, height : 42, bpp : 2,
  transparent : -1,
  palette : myPal, //new Uint16Array([0,65535,23243,52825]),
  buffer : E.toArrayBuffer(atob("AAAAAAL////8JVVVVUJVVVVUJWqqtcJWAAFcJWAAFYJWAAlQJWAAlQJWAA1wAAAAVgAAAAVgAAACVAAAADXAAAABXAAAABWAAAAJUAAAANUAAAANcAAAAFYAAAAlYAAAAlQAAAA1wAAAAVwAAAAVgAAACVAAAADVAAAABXAAAABWAAAAJWAAAAJUAAAANcAAAAFYAAAAFYAAAAlQAAAA1QAAAAVwAAAAVgAAACVAAAADVAAAAAAAAAAAAAAA"))
},d8={
    width : 18, height : 42, bpp : 2,
  transparent : -1,
  palette : myPal, //new Uint16Array([0,65535,6339,33840]),
  buffer : E.toArrayBuffer(atob("AAAAAAD////gNVVVVYFVVVVcFX//1cFcAAFcFcAAFcFcAAFcFcAAFcFcAAFcFcAAFcFcAAFcFcAAFcFcAAFcFcAAFcFUAAlcNVgDVYDVclVwAlVVeAADVVwAANVVYAC1X1XAJVYNVwFXAC1cFcAAFcFcAAFcFcAAFcFcAAFcFcAAFcFcAAFcFcAAFcFcAAFcFcAAFcFcAAFcFcAAFcFcAAFcFeqqlcFVVVVcNVVVVcLVVVVwAAAAAAAAAAAA"))
}, d9={
  width : 18, height : 42, bpp : 2,
  transparent : -1,
  palette : myPal, //new Uint16Array([0,65535,21130,42292]),
  buffer : E.toArrayBuffer(atob("AAAAAAD////ANVVVVwFVVVVYFeqqlYFYAAlYFYAAlYFYAAlYFYAAlYFYAAlYFYAAlYFYAAlYFYAAlYFYAAlYFYAAlYFYAAlYFYAAlYFYAAlYFYAAlYFeqq1YFVVVVYNVVVVYC///1YAAAAlYAAAAlYAAAAlYAAAAlYAAAAlYKoAAlYFcAAlYFcAAlYFcAAlYFcAAlYFcAAlYFcAAlYFcAAlYFcAAlYFVVVVYNVVVVQDVVVXgAAAAAAAAAAAA"))
};

function drawDigit(t,r,n){let a=(n?nmX:startX)[t];t=(n?nmY:startY)[t];EMULATOR&&(a+=80),g.drawImage([d0,d1,d2,d3,d4,d5,d6,d7,d8,d9][r],a,t)}
